const PersoenlicheDatenObject={
  Geschlecht:0,
  Vname:0,
  Nname:0,
  Adresse:0,
  PCode:0,
  City:0,
  Festnetz:0,
  Mobil:0,
  Email:0,
  Barzahlung:0,
  Bankname:0,
  iban:0,
  bank5_12:0,
  bank13_22:0,
  Inhaber:0,
  SteueridCheck:0,
  SteuerID:0,
  Steuerklasse:0,
  Kinder:0,
  Konfession:0,
  Konfessionpa:0,
  AbschlussSchule:0,
  AbschlussAusbildung:0,
  SVNummerfeld:0,
  Staatsbuergerschaft:0,
  GBDatum:0,
  GBName:0,
  GBOrt:0,
  GBLand:0,
  Kassename:0,
  KVArt:0,
}

export default PersoenlicheDatenObject